"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sample_users = exports.sample_tags = exports.sample_foods = void 0;
exports.sample_foods = [
    {
        id: '1',
        name: 'Pizza Pepperoni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        stars: 4.5,
        imageUrl: 'assets/food-1.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '2',
        name: 'Meatball',
        price: 20,
        cookTime: '20-30',
        favorite: true,
        origins: ['persia', 'middle east', 'china'],
        stars: 4.7,
        imageUrl: 'assets/food-2.jpg',
        tags: ['SlowFood', 'Lunch'],
    },
    {
        id: '3',
        name: 'Hamburger',
        price: 5,
        cookTime: '10-15',
        favorite: false,
        origins: ['germany', 'us'],
        stars: 3.5,
        imageUrl: 'assets/food-3.jpg',
        tags: ['FastFood', 'Hamburger'],
    },
    {
        id: '4',
        name: 'Fried Potatoes',
        price: 2,
        cookTime: '15-20',
        favorite: true,
        origins: ['belgium', 'france'],
        stars: 3.3,
        imageUrl: 'assets/food-4.jpg',
        tags: ['FastFood', 'Fry'],
    },
    {
        id: '5',
        name: 'Chicken Soup',
        price: 11,
        cookTime: '40-50',
        favorite: false,
        origins: ['india', 'asia'],
        stars: 3.0,
        imageUrl: 'assets/food-5.jpg',
        tags: ['SlowFood', 'Soup'],
    },
    {
        id: '6',
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: '40-50',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food-6.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '7',
        name: 'Baked Chicken Wings and Legs',
        price: 19,
        cookTime: '40-60',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food11.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '8',
        name: 'Quinoa-Stuffed Bell Pepper',
        price: 23,
        cookTime: '40-60',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food12.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '9',
        name: 'Baked Chicken Wings and Legs',
        price: 26,
        cookTime: '40-60',
        favorite: false,
        origins: ['italy'],
        stars: 4.0,
        imageUrl: 'assets/food13.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '10',
        name: 'Eggplant Parmesan & Linguine',
        price: 26,
        cookTime: '40-50',
        favorite: true,
        origins: ['belgium', 'italy'],
        stars: 4.0,
        imageUrl: 'assets/food14.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '11',
        name: 'Pork Chop with Apple Chutney',
        price: 26,
        cookTime: '40-50',
        favorite: true,
        origins: ['belgium', 'italy'],
        stars: 4.0,
        imageUrl: 'assets/food15.png',
        tags: ['FastFood', 'Pizza'],
    },
    {
        id: '12',
        name: 'Poultry Palace',
        price: 10,
        cookTime: '50-70',
        favorite: true,
        origins: ['belgium', 'italy'],
        stars: 4.0,
        imageUrl: 'assets/food16.png',
        tags: ['FastFood', 'Pizza'],
    },
    {
        id: '13',
        name: 'Mocha Magic Cafe',
        price: 10,
        cookTime: '40-70',
        favorite: false,
        origins: ['belgium', 'italy'],
        stars: 4.0,
        imageUrl: 'assets/food17.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '14',
        name: 'Pork Chop with Apple Chutney',
        price: 12,
        cookTime: '40-70',
        favorite: false,
        origins: ['belgium', 'italy'],
        stars: 4.0,
        imageUrl: 'assets/food18.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '15',
        name: 'Hawaii Vegetarian',
        price: 15,
        cookTime: '40-50',
        favorite: false,
        origins: ['belgium', 'italy'],
        stars: 4.0,
        imageUrl: 'assets/food19.png',
        tags: ['FastFood', 'Pizza', 'Lunch'],
    },
    {
        id: '16',
        name: 'Hawaii Vegetarian Pizza',
        price: 15,
        cookTime: '40-70',
        favorite: true,
        origins: ['belgium', 'italy'],
        stars: 4.0,
        imageUrl: 'assets/food20.jpg',
        tags: ['FastFood', 'Pizza'],
    },
];
exports.sample_tags = [
    { name: 'All', count: 12 },
    { name: 'FastFood', count: 10 },
    { name: 'Pizza', count: 10 },
    { name: 'Lunch', count: 7 },
    { name: 'SlowFood', count: 2 },
    { name: 'Hamburger', count: 1 },
    { name: 'Fry', count: 1 },
    { name: 'Soup', count: 1 },
];
exports.sample_users = [
    {
        name: 'John Doe',
        email: 'john@gmail.com',
        password: '12345',
        address: 'Toronto On',
        isAdmin: true,
    },
    {
        name: 'Jane Doe',
        email: 'Jane@gmail.com',
        password: '12345',
        address: 'Shanghai',
        isAdmin: false,
    },
];
